### PR TITLE
Corrected Readme.rst and added jinja highlight support

### PR DESCRIPTION
**Pull request by Neocid**
Change outdated information about package manager for sublime
Provided "how to" install this module
Added "jinja" highlight

### CODE REVIEW

**Comment by eshelman** [comment]
Would you please give more information on why are you correcting the README by removing references to Package Control? I've had no trouble installing via Package Control.

**Comment by anlutro** [comment]
I don't see why you'd want jinja files to have SLS syntax as opposed to jinja syntax.

**Comment by Neocid** [comment]
My jinja files are not syntax colored without the modification I made.

Can you point me out what I have to change to make it look like a jinja file?

**Comment by anlutro** [comment]
This is definitely a flaw in the jinja package, but what you can do is open a file with the .jinja extension, then in the menu go to View → Syntax → Open all with current extension as → Jinja.

**Comment by Neocid** [comment]
Oki, I haven't found the option. Let me close this pull request.

**Pull request closed without merging**
